//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Threading;
using log4net.Config;
using NHibernate.Cache;
using NHibernate.Caches.Common.Tests;
using NUnit.Framework;

namespace NHibernate.Caches.EnyimMemcached.Tests
{
	using System.Threading.Tasks;
	public partial class MemCacheFixture : CacheFixture
	{

		[Test]
		public async Task TestRemove144Async()
		{
			string key = "keyTestRemove144";
			string value = "value";

			//memcached 1.4+ drops support for expiration time specified for Delete operations
			//therefore if you install memcached 1.4.4 this test will fail unless corresponding fix is implemented in MemCacheClient.cs
			//the test will fail because Remove won't actually delete the item from the cache!
			//the error you will see in the log is: "Error deleting key: nunit@key1.  Server response: CLIENT_ERROR bad command line format.  Usage: delete <key> [noreply]"

			//Now, Memcached.ClientLibrary incorrectly divides expiration time for Delete operation by 1000
			//(for Add and Set operations the expiration time is calculated correctly)
			//that's why we need to set expiration to 20000, otherwise it will be treated as 20ms which is too small to be sent to server (the minimum value is 1 second)
			var props = GetDefaultProperties();
			props["expiration"] = "20000";

			//disabling lingering delete will cause the item to get immediately deleted
			//this parameter is NEW and the code to make it work is part of the proposed fix
			props.Add("lingering_delete_disabled", "true");

			var cache = DefaultProvider.BuildCache("TestRemove144", props);
			Assert.That(cache, Is.Not.Null, "no cache returned");

			// add the item
			await (cache.PutAsync(key, value, CancellationToken.None));
			await (Task.Delay(1000));

			// make sure it's there
			var item = await (cache.GetAsync(key, CancellationToken.None));
			Assert.That(item, Is.Not.Null, "item just added is not there");

			// remove it
			await (cache.RemoveAsync(key, CancellationToken.None));

			// make sure it's not there
			item = await (cache.GetAsync(key, CancellationToken.None));
			Assert.That(item, Is.Null, "item still exists in cache");
		}
	}
}
